# Generated by Django 3.1.7 on 2021-03-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
