# Generated by Django 3.1.7 on 2021-03-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0003_content_boolean'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='boolean',
            new_name='happy',
        ),
    ]
